services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
    ports:
      - 13378:80 #do not change :80
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./ebooks:/ebooks
      - ./config:/config
      - ./metadata:/metadata
    restart: unless-stopped
